### ISSUE TITLE
Packaged libmonero-cpp.dll does not seem to load with current MSYS2 boost

### ISSUE THREAD

**Issue by mr-nv** [woodser/monero-java#111]
Hello.

I installed MSYS2 and installed all the dependencies listed here:
https://github.com/woodser/monero-cpp?tab=readme-ov-file#windows

When calling MoneroUtils.loadNativeLibrary() with monero-java being added through Gradle (not built from source), it fails with the following error:
```
Caused by: java.lang.UnsatisfiedLinkError: (temp path)\libmonero-cpp.dll: The specified procedure could not be found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at monero.common.MoneroUtils.loadNativeLibrary(MoneroUtils.java:114)
```

When using [Dependencies](https://github.com/lucasg/Dependencies) to find out more about the error, it appears that monero-cpp tries to import some functions from boost's filesystem library that are no longer present:
![Screenshot_5765](https://github.com/user-attachments/assets/2858ac46-8165-4d77-8141-6d82202af4f6)

The version of boost that I have is 1.86.0:
![image](https://github.com/user-attachments/assets/840a45f8-6823-4b01-8a86-9c9d1fc6e063)

Is this a real problem or did I install boost somehow wrong?

**Comment by woodser** [comment]
Hm, I'm running mingw-w64-x86_64-boost 1.84.0-1 in case that's the problem.

Because these are shared libraries, the dependencies need to be satisfied on the host platform unfortunately.

**Comment by mr-nv** [comment]
Hello again. Yes, copying an older version of libboost_filesystem-mt.dll from here:
https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-boost-1.84.0-1-any.pkg.tar.zst

Makes the library work since the imports are all there.

**Comment by woodser** [comment]
Marking this as complete. There's an issue open to build to static libraries so these dependency differences aren't a problem: https://github.com/woodser/monero-java/pull/105

**Comment by mr-nv** [comment]
Yeah that would be much better, thanks.

пт, 13 дек. 2024 г., 20:22 woodser ***@***.***>:
